// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rurnawvbzeziyohzamfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cm5hd3ZiemV6aXlvaHphbWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODI1MzcsImV4cCI6MjA2NjU1ODUzN30.ppwVoUMaDSK8epW_G0aklXA2CKaeFoNFByZ3X7oZ7LM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);